topology:
  serial:
    step_processing_order:
      - 1
    body:
      - machine:
          step_processing_order:
            - 2
      - parallel:
          step_processing_order:
            - 3
          body:
            - serial:
                step_processing_order:
                  - 4
                body:
                  - machine:
                      step_processing_order:
                        - 5
                  - machine:
                      step_processing_order:
                        - 6
                  - machine:
                      step_processing_order:
                        - 7
            - serial:
                step_processing_order:
                  []
                body:
                  - machine:
                      step_processing_order:
                        []
                  - machine:
                      step_processing_order:
                        []
                  - machine:
                      step_processing_order:
                        []
            - serial:
                step_processing_order:
                  []
                body:
                  - machine:
                      step_processing_order:
                        []
                  - machine:
                      step_processing_order:
                        []
                  - machine:
                      step_processing_order:
                        []
      - machine:
          step_processing_order:
            - 8
jobs:
  - job_id: 1
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 1
      - machine_id: 2
        path_node_id: 2
        processing_step_id: 2
      - machine_id: 3
        path_node_id: 3
        processing_step_id: 3
      - machine_id: 5
        path_node_id: 4
        processing_step_id: 4
      - machine_id: 8
        path_node_id: 5
        processing_step_id: 5
      - machine_id: 9
        path_node_id: 6
        processing_step_id: 6
      - machine_id: 10
        path_node_id: 7
        processing_step_id: 7
      - machine_id: 4
        path_node_id: 16
        processing_step_id: 8