topology:
  parallel:
    step_processing_order:
      - 1
    body:
      - machine:
          step_processing_order:
            - 2
      - machine:
          step_processing_order:
            []
jobs:
  - job_id: 1
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 1
      - machine_id: 2
        path_node_id: 2
        processing_step_id: 2