//
// Created by mihael on 5/29/24.
//

#ifndef SBGPINSTRUCTIONTYPE_H
#define SBGPINSTRUCTIONTYPE_H

enum SBGPInstructionType {
    SBGP_PUSH_PARAM,
    SBGP_PUSH_CONSTANT,
    SBGP_UNARY_MINUS,
    SBGP_PLUS,
    SBGP_MINUS,
    SBGP_TIMES,
    SBGP_DIVIDE,
    SBGP_SQUARE,
    SBGP_ROOT,
    SBGP_BRANCH,
    SBGP_NOP
};

#endif //SBGPINSTRUCTIONTYPE_H
