//
// Created by mihael on 29/04/23.
//

#ifndef SCHEDULING_NODETYPE_H
#define SCHEDULING_NODETYPE_H

enum NodeType {
    ABSTRACT_NODE_TYPE,
    MACHINE_NODE_TYPE,
    SERIAL_GROUP_NODE_TYPE,
    PARALLEL_GROUP_NODE_TYPE,
    ROUTE_GROUP_NODE_TYPE,
    OPEN_GROUP_NODE_TYPE
};

#endif //SCHEDULING_NODETYPE_H
