//
// Created by mihael on 29/04/23.
//

#ifndef SCHEDULING_TOPOLOGYELEMENTTYPE_H
#define SCHEDULING_TOPOLOGYELEMENTTYPE_H

enum TopologyElementType {
    ABSTRACT_TOPOLOGY_ELEMENT,
    MACHINE_TOPOLOGY_ELEMENT,
    SERIAL_GROUP_TOPOLOGY_ELEMENT,
    PARALLEL_GROUP_TOPOLOGY_ELEMENT,
    ROUTE_GROUP_TOPOLOGY_ELEMENT,
    OPEN_GROUP_TOPOLOGY_ELEMENT
};

#endif //SCHEDULING_TOPOLOGYELEMENTTYPE_H
