topology:
  serial:
    step_processing_order:
      - 1
    body:
      - machine:
          step_processing_order:
            - 2
      - route:
          step_processing_order:
            - 3
          body:
            - machine:
                step_processing_order:
                  []
            - serial:
                step_processing_order:
                  []
                body:
                  - machine:
                      step_processing_order:
                        []
                  - machine:
                      step_processing_order:
                        []
                  - machine:
                      step_processing_order:
                        []
            - machine:
                step_processing_order:
                  []
      - machine:
          step_processing_order:
            - 4
jobs:
  - job_id: 1
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 1
      - machine_id: 2
        path_node_id: 2
        processing_step_id: 2
      - machine_id: 3
        path_node_id: 3
        processing_step_id: 3
      - machine_id: 4
        path_node_id: 4
        processing_step_id: 4