topology:
  serial:
    step_processing_order:
      - 1
      - 5
      - 9
      - 13
      - 17
      - 21
      - 25
      - 29
      - 33
    body:
      - parallel:
          step_processing_order:
            - 2
            - 6
            - 10
            - 14
            - 18
            - 22
            - 26
            - 30
            - 34
          body:
            - machine:
                step_processing_order:
                  - 3
                  - 7
                  - 11
            - machine:
                step_processing_order:
                  - 15
                  - 19
                  - 23
            - machine:
                step_processing_order:
                  - 27
                  - 31
                  - 35
      - machine:
          step_processing_order:
            - 4
            - 8
            - 12
            - 16
            - 28
            - 20
            - 32
            - 24
            - 36
jobs:
  - job_id: 1
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 1
      - machine_id: 2
        path_node_id: 2
        processing_step_id: 2
      - machine_id: 3
        path_node_id: 3
        processing_step_id: 3
      - machine_id: 6
        path_node_id: 6
        processing_step_id: 4
  - job_id: 2
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 5
      - machine_id: 2
        path_node_id: 2
        processing_step_id: 6
      - machine_id: 3
        path_node_id: 3
        processing_step_id: 7
      - machine_id: 6
        path_node_id: 6
        processing_step_id: 8
  - job_id: 3
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 9
      - machine_id: 2
        path_node_id: 2
        processing_step_id: 10
      - machine_id: 3
        path_node_id: 3
        processing_step_id: 11
      - machine_id: 6
        path_node_id: 6
        processing_step_id: 12
  - job_id: 4
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 13
      - machine_id: 2
        path_node_id: 2
        processing_step_id: 14
      - machine_id: 4
        path_node_id: 4
        processing_step_id: 15
      - machine_id: 6
        path_node_id: 6
        processing_step_id: 16
  - job_id: 5
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 17
      - machine_id: 2
        path_node_id: 2
        processing_step_id: 18
      - machine_id: 4
        path_node_id: 4
        processing_step_id: 19
      - machine_id: 6
        path_node_id: 6
        processing_step_id: 20
  - job_id: 6
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 21
      - machine_id: 2
        path_node_id: 2
        processing_step_id: 22
      - machine_id: 4
        path_node_id: 4
        processing_step_id: 23
      - machine_id: 6
        path_node_id: 6
        processing_step_id: 24
  - job_id: 7
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 25
      - machine_id: 2
        path_node_id: 2
        processing_step_id: 26
      - machine_id: 5
        path_node_id: 5
        processing_step_id: 27
      - machine_id: 6
        path_node_id: 6
        processing_step_id: 28
  - job_id: 8
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 29
      - machine_id: 2
        path_node_id: 2
        processing_step_id: 30
      - machine_id: 5
        path_node_id: 5
        processing_step_id: 31
      - machine_id: 6
        path_node_id: 6
        processing_step_id: 32
  - job_id: 9
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 33
      - machine_id: 2
        path_node_id: 2
        processing_step_id: 34
      - machine_id: 5
        path_node_id: 5
        processing_step_id: 35
      - machine_id: 6
        path_node_id: 6
        processing_step_id: 36