topology:
  parallel:
    step_processing_order:
      - 1
      - 3
      - 5
      - 7
      - 9
      - 11
    body:
      - machine:
          step_processing_order:
            - 2
            - 4
      - machine:
          step_processing_order:
            - 6
            - 8
      - machine:
          step_processing_order:
            - 10
            - 12
jobs:
  - job:
      id: 1
      processing_route:
        - entry:
            machine_id: 1
            processing_step_id: 1
        - entry:
            machine_id: 2
            processing_step_id: 2
  - job:
      id: 2
      processing_route:
        - entry:
            machine_id: 1
            processing_step_id: 3
        - entry:
            machine_id: 2
            processing_step_id: 4
  - job:
      id: 3
      processing_route:
        - entry:
            machine_id: 1
            processing_step_id: 5
        - entry:
            machine_id: 3
            processing_step_id: 6
  - job:
      id: 4
      processing_route:
        - entry:
            machine_id: 1
            processing_step_id: 7
        - entry:
            machine_id: 3
            processing_step_id: 8
  - job:
      id: 5
      processing_route:
        - entry:
            machine_id: 1
            processing_step_id: 9
        - entry:
            machine_id: 4
            processing_step_id: 10
  - job:
      id: 6
      processing_route:
        - entry:
            machine_id: 1
            processing_step_id: 11
        - entry:
            machine_id: 4
            processing_step_id: 12