topology:
  parallel:
    step_processing_order:
      - 1
      - 6
      - 11
      - 16
      - 21
      - 26
    body:
      - serial:
          step_processing_order:
            - 2
            - 17
          body:
            - machine:
                step_processing_order:
                  - 3
                  - 18
            - machine:
                step_processing_order:
                  - 4
                  - 19
            - machine:
                step_processing_order:
                  - 5
                  - 20
      - serial:
          step_processing_order:
            - 7
            - 22
          body:
            - machine:
                step_processing_order:
                  - 8
                  - 23
            - machine:
                step_processing_order:
                  - 9
                  - 24
            - machine:
                step_processing_order:
                  - 10
                  - 25
      - serial:
          step_processing_order:
            - 12
            - 27
          body:
            - machine:
                step_processing_order:
                  - 13
                  - 28
            - machine:
                step_processing_order:
                  - 14
                  - 29
            - machine:
                step_processing_order:
                  - 15
                  - 30
jobs:
  - job_id: 1
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 1
      - machine_id: 2
        path_node_id: 2
        processing_step_id: 2
      - machine_id: 5
        path_node_id: 3
        processing_step_id: 3
      - machine_id: 6
        path_node_id: 4
        processing_step_id: 4
      - machine_id: 7
        path_node_id: 5
        processing_step_id: 5
  - job_id: 2
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 6
      - machine_id: 3
        path_node_id: 6
        processing_step_id: 7
      - machine_id: 8
        path_node_id: 7
        processing_step_id: 8
      - machine_id: 9
        path_node_id: 8
        processing_step_id: 9
      - machine_id: 10
        path_node_id: 9
        processing_step_id: 10
  - job_id: 3
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 11
      - machine_id: 4
        path_node_id: 10
        processing_step_id: 12
      - machine_id: 11
        path_node_id: 11
        processing_step_id: 13
      - machine_id: 12
        path_node_id: 12
        processing_step_id: 14
      - machine_id: 13
        path_node_id: 13
        processing_step_id: 15
  - job_id: 4
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 16
      - machine_id: 2
        path_node_id: 2
        processing_step_id: 17
      - machine_id: 5
        path_node_id: 3
        processing_step_id: 18
      - machine_id: 6
        path_node_id: 4
        processing_step_id: 19
      - machine_id: 7
        path_node_id: 5
        processing_step_id: 20
  - job_id: 5
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 21
      - machine_id: 3
        path_node_id: 6
        processing_step_id: 22
      - machine_id: 8
        path_node_id: 7
        processing_step_id: 23
      - machine_id: 9
        path_node_id: 8
        processing_step_id: 24
      - machine_id: 10
        path_node_id: 9
        processing_step_id: 25
  - job_id: 6
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 26
      - machine_id: 4
        path_node_id: 10
        processing_step_id: 27
      - machine_id: 11
        path_node_id: 11
        processing_step_id: 28
      - machine_id: 12
        path_node_id: 12
        processing_step_id: 29
      - machine_id: 13
        path_node_id: 13
        processing_step_id: 30