topology:
  serial:
    step_processing_order:
      - 1
    body:
      - parallel:
          step_processing_order:
            - 2
          body:
            - serial:
                step_processing_order:
                  []
                body:
                  - machine:
                      step_processing_order:
                        []
                  - machine:
                      step_processing_order:
                        []
                  - machine:
                      step_processing_order:
                        []
            - serial:
                step_processing_order:
                  - 3
                body:
                  - machine:
                      step_processing_order:
                        - 4
                  - parallel:
                      step_processing_order:
                        - 5
                      body:
                        - serial:
                            step_processing_order:
                              []
                            body:
                              - machine:
                                  step_processing_order:
                                    []
                              - machine:
                                  step_processing_order:
                                    []
                        - serial:
                            step_processing_order:
                              []
                            body:
                              - machine:
                                  step_processing_order:
                                    []
                              - machine:
                                  step_processing_order:
                                    []
                        - serial:
                            step_processing_order:
                              - 6
                            body:
                              - machine:
                                  step_processing_order:
                                    - 7
                              - machine:
                                  step_processing_order:
                                    - 8
                  - machine:
                      step_processing_order:
                        - 9
            - open:
                step_processing_order:
                  []
                body:
                  - machine:
                      step_processing_order:
                        []
                  - machine:
                      step_processing_order:
                        []
                  - machine:
                      step_processing_order:
                        []
                  - machine:
                      step_processing_order:
                        []
      - machine:
          step_processing_order:
            - 10
      - machine:
          step_processing_order:
            - 11
      - parallel:
          step_processing_order:
            - 12
          body:
            - machine:
                step_processing_order:
                  - 13
            - machine:
                step_processing_order:
                  []
            - machine:
                step_processing_order:
                  []
jobs:
  - job_id: 1
    processing_route:
      - machine_id: 1
        path_node_id: 1
        processing_step_id: 1
      - machine_id: 2
        path_node_id: 2
        processing_step_id: 2
      - machine_id: 7
        path_node_id: 7
        processing_step_id: 3
      - machine_id: 12
        path_node_id: 8
        processing_step_id: 4
      - machine_id: 13
        path_node_id: 9
        processing_step_id: 5
      - machine_id: 17
        path_node_id: 16
        processing_step_id: 6
      - machine_id: 22
        path_node_id: 17
        processing_step_id: 7
      - machine_id: 23
        path_node_id: 18
        processing_step_id: 8
      - machine_id: 14
        path_node_id: 19
        processing_step_id: 9
      - machine_id: 3
        path_node_id: 21
        processing_step_id: 10
      - machine_id: 4
        path_node_id: 22
        processing_step_id: 11
      - machine_id: 5
        path_node_id: 23
        processing_step_id: 12
      - machine_id: 28
        path_node_id: 24
        processing_step_id: 13