topology:
  open:
    step_processing_order:
      - 1
      - 3
    body:
      - machine:
          step_processing_order:
            - 4
      - machine:
          step_processing_order:
            - 2
            - 5
            - 6
            - 7
jobs:
  - job_id: 1
    processing_route:
      - machine_id: 1
        processing_step_id: 1
      - machine_id: 3
        processing_step_id: 2
  - job_id: 2
    processing_route:
      - machine_id: 1
        processing_step_id: 3
      - machine_id: 2
        processing_step_id: 4
      - machine_id: 3
        processing_step_id: 5
      - machine_id: 3
        processing_step_id: 6
      - machine_id: 3
        processing_step_id: 7