//
// Created by mihael on 29/04/23.
//

#ifndef SCHEDULING_EVENTTYPE_H
#define SCHEDULING_EVENTTYPE_H

enum EventType {
    ABSTRACT,
    SYSTEM_EXIT,
    SYSTEM_EXIT_FORCED,
    SYSTEM_ENTRY,
    MACHINE_EXIT,
    MACHINE_EXIT_BATCH,
    MACHINE_EXIT_FORCED,
    MACHINE_EXIT_FORCED_BATCH,
    MACHINE_BUFFER_ENTRY,
    PREREQUISITES_WAIT_START,
    PREREQUISITES_WAIT_END,
    PREEMPT,
    PREEMPT_BATCH,
    SETUP_START,
    SETUP_END,
    SETUP_CANCEL,
    BREAKDOWN_START,
    BREAKDOWN_END,
    MACHINE_ENTRY,
    MACHINE_ENTRY_BATCH,
    MACHINE_BUFFER_ENTRY_REQUEST_ASYNCHRONOUS,
    MACHINE_BUFFER_ENTRY_REQUEST_SYNCHRONOUS,
    WAKE_MACHINE,
};

#endif //SCHEDULING_EVENTTYPE_H
