topology:
  serial:
    step_processing_order:
      - 1
      - 7
    body:
      - parallel:
          step_processing_order:
            - 2
            - 8
          body:
            - machine:
                step_processing_order:
                  - 3
            - machine:
                step_processing_order:
                  - 9
      - machine:
          step_processing_order:
            - 4
            - 10
      - machine:
          step_processing_order:
            - 5
            - 11
      - machine:
          step_processing_order:
            - 12
            - 6
jobs:
  - job:
      id: 1
      processing_route:
        - entry:
            machine_id: 1
            processing_step_id: 1
        - entry:
            machine_id: 2
            processing_step_id: 2
        - entry:
            machine_id: 6
            processing_step_id: 3
        - entry:
            machine_id: 3
            processing_step_id: 4
        - entry:
            machine_id: 4
            processing_step_id: 5
        - entry:
            machine_id: 5
            processing_step_id: 6
  - job:
      id: 2
      processing_route:
        - entry:
            machine_id: 1
            processing_step_id: 7
        - entry:
            machine_id: 2
            processing_step_id: 8
        - entry:
            machine_id: 7
            processing_step_id: 9
        - entry:
            machine_id: 3
            processing_step_id: 10
        - entry:
            machine_id: 4
            processing_step_id: 11
        - entry:
            machine_id: 5
            processing_step_id: 12