//
// Created by mihael on 5/27/24.
//

#ifndef LGPINSTRUCTIONTYPES_H
#define LGPINSTRUCTIONTYPES_H

enum LGPInstructionType {
    LGP_LOAD_PARAM,
    LGP_LOAD_CONSTANT,
    LGP_UNARY_MINUS,
    LGP_PLUS,
    LGP_MINUS,
    LGP_TIMES,
    LGP_DIVIDE,
    LGP_SQUARE,
    LGP_ROOT,
    LGP_CONDITION,
    LGP_NOP
};

#endif //LGPINSTRUCTIONTYPES_H
